## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-STATE
  - PROVIDER-INFRA-SETUP
  - STATEFUL-APP-DEPLOY
  # - APP-FUNC-TEST
  # - APP-CHAOS-TEST
  - CLUSTER-CLEANUP

openshift-cluster-state:
  image: atulabhi/kops:v8
  stage: CLUSTER-STATE
  script:
   - echo "PIPELINEMODE=$CI_PIPELINE_SOURCE"
   - chmod 775 ./scripts/providers/cluster-state
   - ./scripts/providers/cluster-state

openebs-openshift-deploy:
  image: atulabhi/kops:v8
  stage: PROVIDER-INFRA-SETUP
  script:
   - chmod 775 ./scripts/providers/infra-setup
   - ./scripts/providers/infra-setup pod
  dependencies:
    - openshift-cluster-state

.app_deploy_template:
  image: atulabhi/kops:v8
  stage: STATEFUL-APP-DEPLOY 
  dependencies:
    - openebs-openshift-deploy

percona-jiva-run/load/check 0:2:
  extends: .app_deploy_template
  script: 
   - chmod 755 ./scripts/apps/percona/percona-app-deploy-jiva
   - ./scripts/apps/percona/percona-app-deploy-jiva

cluster-cleanup:
  image: atulabhi/kops:v8
  stage: CLUSTER-CLEANUP
  script:
    - chmod 775 ./scripts/providers/cluster-cleanup
    - ./scripts/providers/cluster-cleanup
